# --- Section 4: Kubernetes Deployment Manifest ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildlife-api-deployment
spec:
  # replicas dynamically scaled
  replicas: 2 
  selector:
    matchLabels:
      app: wildlife-api
  template:
    metadata:
      labels:
        app: wildlife-api
    spec:
      containers:
      - name: wildlife-app
        # Using the image you just pushed to GCP Artifact Registry
        image: australia-southeast1-docker.pkg.dev/composed-card-490512-r1/wildlife-repo/wildlife-api:vm-v2
        ports:
        - containerPort: 8000

        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5

        # Defining resource requests/limits is critical for GKE Autopilot efficiency
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1.0"
            memory: "2Gi"
---
# --- Section 4: Public Service (Load Balancer) ---
apiVersion: v1
kind: Service
metadata:
  name: wildlife-api-service
  namespace: default
spec:
  # LoadBalancer type will provision a real public IP address on GCP
  type: LoadBalancer
  selector:
    app: wildlife-api
  ports:
    - protocol: TCP
      port: 80 # Public port
      targetPort: 8000 # Internal container port