# --- Section 4: Kubernetes Deployment Manifest ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildlife-api-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wildlife-api
  template:
    metadata:
      labels:
        app: wildlife-api
    spec:
      containers:
        - name: wildlife-app
          image: australia-southeast1-docker.pkg.dev/composed-card-490512-r1/wildlife-repo/wildlife-api:vm-v6
          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3

          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: wildlife-api-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: wildlife-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080